#Nome do Workflow
name: CI-CD
#Eventos que vão disparar 
on:
  push:
    branches: [ main ]  
  #permitir que eu dispare manualmente
  workflow_dispatch:
jobs:
  build:
    #Agente de execução - set up de maquina
    runs-on: ubuntu-latest
    #execuções que vou ter no meu job
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
